// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// Do not modify this file, it will be overwritten.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      // Anda perlu menambahkan konfigurasi Android di sini jika akan build ke Android
      // Biasanya didapat dari file google-services.json
      // Untuk sementara, kita bisa menggunakan konfigurasi web sebagai placeholder
      // atau melempar error agar tidak lupa.
        return web;
      case TargetPlatform.iOS:
      // Sama seperti Android, perlu konfigurasi dari file GoogleService-Info.plist
        return web;
      case TargetPlatform.macOS:
      // Sama seperti iOS
        return web;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD4UnJGz7A7O_p0kh1HgNh79oUNAnXQbRA",
    appId: "1:883341895343:web:b0b10bdf4ee2aa2ad2165a",
    messagingSenderId: "883341895343",
    projectId: "racketlog-84b9c",
    authDomain: "racketlog-84b9c.firebaseapp.com",
    storageBucket: "racketlog-84b9c.appspot.com", // Disesuaikan sedikit untuk Flutter
    measurementId: "G-CLCSM8QLWR",
  );
}
